2024-05-28 19:49:28,768 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:49:29,772 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x12454ea50>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:51:55,484 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:51:56,488 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x146dba2a0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:51:56,488 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:01,494 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:02,497 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1470d1d90>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:02,497 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:07,506 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:08,509 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1470d24b0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:08,509 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:13,513 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:14,517 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1470d2bd0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:14,517 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:19,533 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:20,537 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x146dba990>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:20,538 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:25,543 - ERROR - Failed to connect to the device after multiple attempts.
2024-05-28 19:52:32,530 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:33,533 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x13a5dba70>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:33,534 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:38,548 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:39,552 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x13a60dfa0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:39,553 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:44,559 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:45,562 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x13a60e6c0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:45,563 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:50,568 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:50,571 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13a60ede0>: Failed to establish a new connection: [Errno 12] Cannot allocate memory'))
2024-05-28 19:52:50,571 - INFO - Retrying in 5 seconds...
2024-05-28 19:52:55,581 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:52:56,584 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x13a5db4d0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:52:56,585 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:01,589 - ERROR - Failed to connect to the device after multiple attempts.
2024-05-28 19:53:07,468 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:53:08,472 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x130ad1820>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:53:08,473 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:13,480 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:53:14,483 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x130ad2000>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:53:14,483 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:19,492 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:53:20,499 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x130ad2720>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:53:20,499 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:25,505 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:53:26,508 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x130ad2e40>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:53:26,508 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:31,525 - DEBUG - Starting new HTTP connection (1): 10.23.10.45:80
2024-05-28 19:53:32,529 - ERROR - Error connecting to device: HTTPConnectionPool(host='10.23.10.45', port=80): Max retries exceeded with url: /api/slot/0/io/ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x130a28ad0>, 'Connection to 10.23.10.45 timed out. (connect timeout=1)'))
2024-05-28 19:53:32,530 - INFO - Retrying in 5 seconds...
2024-05-28 19:53:37,533 - ERROR - Failed to connect to the device after multiple attempts.
